language: node_js
node_js: 12.13.0
sudo: false
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
  - yarn install
script:
  - yarn build
  - yarn test
deploy:
  edge: true
  skip_cleanup: true
  on:
    branch: master
  provider: firebase
env:
  global:
    secure: lrKSqI/F5J1IqX4Zy1ESlaqk+Gnymvp1iyCCuoB269567FoxNG7sRb4F3AaSYsGbtUQhghSF24ZdHZWANvGR2JVEvoD+K8eR04B3CtFYtIq4BOvGgbj4XtbsrLEKewrLpCGGczg4ZvGnQocmBuykMVpc07LCYB8JalL5ZPYq5UHp4wx0p0dO2VEpbGdUit3gOPRAhfQyGyRlspOhv/+bQPeOKpReaciXt9ldOclA1eKmEJBAHjPL09OkVX0eDfD7KSabu6pq9G89jPNc0V2gT2H31L84GAVqWioQuSd/C/4kLLC3yM2QENog+QRsKmXhusoNNH11p8u+EFQ3tDoCShrmAbakY9eUan3ZgYQzJZXhacsRFWY7SqSYPSFR5jwGDy71aY+OgooXiR9O9fhW4DodoDkR1zvdqg1n8oY93L4XsBSf876eCIJYnkGcMJk7M8MtcFUjOFl/YgHs5kUktxjtvcx6yoiCc2SmUlDoaWV0f8DApHJF4yeWMUWQAS+NVgLF+SDu8ooE+IO1bbcw+bn7Ojeh4SQcO2qu/rDYjZSPuETf7+urYTIbfV5YdbucVweXKoKosTRw7ZF21h5Tnya4s6b3LMMl/N4c5vNpxi0UPcIAci0tfVMbpUUo6r8aLvQo7f5Vdfwyx1tx10pAIlBWbu+2Mf+qfP3pAZVjHHQ=
